import { TransferEngine } from './downloads/engine';
import { registerTransferIpc } from './downloads/transfer-ipc';
import { DirectoryGrants } from './downloads/paths';
import { DownloadPlanner } from './downloads/planner';
import { registerPlanningIpc } from './downloads/ipc';
import { LibraryStore } from './library/store';
import { registerLibraryIpc } from './library/ipc';
import { app, BrowserWindow, dialog, ipcMain, session } from 'electron';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { SettingsStore } from './settings-store';
import { defaultSettings, settingsSchema } from '../shared/desktop';
import { isTrustedSender } from './security';
import { registerCatalogIpc } from './catalog/ipc';
import { CatalogClient } from './catalog/client';
import { PlaybackController } from './playback/controller';
import { readStorageSnapshot } from './storage';
import { protocol } from 'electron';

protocol.registerSchemesAsPrivileged([{ scheme: 'castbox-media', privileges: { standard: true, secure: true, supportFetchAPI: true, stream: true } }]);

app.setName('Castbox Fresh');
// Isolate this restart from data generated by previous implementations.
app.setPath('userData', join(app.getPath('appData'), 'Castbox Fresh'));
const page = pathToFileURL(join(__dirname, '../ai-studio-frontend/dist/index.html')).href;
let window: BrowserWindow | null = null;

app.whenReady().then(() => {
  const destination = join(app.getPath('downloads'), 'Castbox');
  const store = new SettingsStore(join(app.getPath('userData'), 'settings.json'), defaultSettings(destination));
  const selectedDirectories = new Set([destination]);
  let choosingDirectory = false;
  session.defaultSession.setPermissionRequestHandler((_wc, _permission, callback) => callback(false));
  session.defaultSession.setPermissionCheckHandler(() => false);
  const register = (name: string, handler: (payload: unknown) => unknown) => {
    ipcMain.handle(name, async (event, payload: unknown) => {
      if (!window || event.sender !== window.webContents || !isTrustedSender(event.senderFrame?.url, page, event.senderFrame === window.webContents.mainFrame)) {
        return { ok: false, error: 'Request denied.' };
      }
      try { return { ok: true, value: await handler(payload) }; }
      catch (error) { return { ok: false, error: error instanceof Error && !('issues' in error) ? error.message : 'Invalid settings. Check the filename template and values.' }; }
    });
  };
    const catalog = new CatalogClient(fetch, 10_000, () => ({
      token: store.currentSettings.userToken,
      secret: store.currentSettings.userTokenSecret,
    }));
    registerCatalogIpc(() => window, page, catalog);
  const library = new LibraryStore(join(app.getPath('userData'), 'library.sqlite'));
  registerLibraryIpc(() => window, page, library);
  const playback = new PlaybackController(library);
  session.defaultSession.protocol.handle('castbox-media', request => playback.serve(request));
  register('playback:snapshot', () => playback.snapshot());
  register('playback:clear-history', input => { if (input !== undefined) throw new Error('Unexpected playback input.'); library.clearPlaybackHistory(); });
  register('playback:source', input => playback.source(input));
  register('playback:progress', input => playback.saveProgress(input));
  register('playback:queue', input => playback.replaceQueue(input));

  register('app:info', () => ({ version: app.getVersion(), platform: process.platform, mode: 'live-catalog' }));
  register('settings:read', () => store.read());
  register('settings:save', async input => {
    const settings = settingsSchema.parse(input);
    const current = await store.read();
    if (!selectedDirectories.has(settings.downloadDestination) && settings.downloadDestination !== current.downloadDestination) {
      throw new Error('Choose a download folder using Change Folder before saving.');
    }
    return store.save(settings);
  });
  const grants = new DirectoryGrants();
  const planner = new DownloadPlanner(grants, library);
  const transfers = new TransferEngine(library, grants);
  registerTransferIpc(() => window, page, transfers);
  const readStorage = async () => readStorageSnapshot((await store.read()).downloadDestination, await transfers.completedFilesBytes(), await session.defaultSession.getCacheSize());
  register('storage:read', input => { if (input !== undefined) throw new Error('Unexpected storage request.'); return readStorage(); });
  register('storage:clear-cache', async input => {
    if (input !== undefined) throw new Error('Unexpected storage request.');
    await session.defaultSession.clearCache();
    return readStorage();
  });
  void store.read().then(settings => transfers.setConcurrency({ concurrency: settings.downloadConcurrency })).catch(() => {});
  let quitReady = false;
  app.on('before-quit', event => {
    if (quitReady) return;
    event.preventDefault();
    void transfers.suspend().finally(() => { planner.revoke(); library.close(); quitReady = true; app.quit(); });
  });
  const chooseDirectory = async () => {
    if (!window || choosingDirectory) throw new Error('A folder dialog is already open.');
    choosingDirectory = true;
    try {
      const result = await dialog.showOpenDialog(window, { title: 'Choose download folder', properties: ['openDirectory', 'createDirectory'] });
      const path = result.canceled ? null : result.filePaths[0] ?? null;
      if (!path) return null;
      const grant = await grants.issue(path);
      selectedDirectories.add(grant.path);
      return grant;
    } finally { choosingDirectory = false; }
  };
  register('settings:choose-directory', chooseDirectory);
  registerPlanningIpc(() => window, page, planner, chooseDirectory);
  const open = () => {
    window = new BrowserWindow({ width: 1440, height: 1000, minWidth: 960, minHeight: 700,
      title: 'Castbox Downloader — Live catalog',
      webPreferences: { preload: join(__dirname, 'preload.cjs'), contextIsolation: true, sandbox: true, nodeIntegration: false, webviewTag: false } });
    window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
    window.webContents.on('will-navigate', (event) => event.preventDefault());
    window.webContents.on('will-attach-webview', event => event.preventDefault());
    window.on('page-title-updated', event => event.preventDefault());
    window.on('closed', () => { window = null; if (!quitReady) void transfers.suspend().finally(() => planner.revoke()); });
    void window.loadURL(page);
  };
  open();
  app.on('activate', () => { if (!window) open(); });
});
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
